name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

transparent_image: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# =========================
#  Icono de la aplicación
# =========================
flutter_launcher_icons:
  android: true
  ios: true

  # --- Requerido: imagen legacy (fallback) ---
  # Puedes usar la misma que el foreground si no tienes otra
  image_path_android: assets/icon/hx192.png
  image_path_ios: assets/icon/hx192.png

  # --- Android adaptive icon (moderno) ---
  adaptive_icon_background: "#00BFA6"                  # color de fondo
  adaptive_icon_foreground: assets/icon/hx192.png # SOLO la huella (PNG transparente)

  min_sdk_android: 21
  remove_alpha_ios: true

# =========================
#  Splash Screen nativo
# =========================
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/hx192.png
  android: true
  ios: true
  web: true
