[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
restartPolicyType = "ON_FAILURE"

[env]
# Puedes fijar aquí configs de DB si luego agregas MySQL
# DB_HOST = "mysql.railway.internal"
# DB_USER = "root"
# DB_PASS = "PKcvvnUTFlVzITtTCyOXAfvoelKhaPwS"
